In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('demo.csv',error_bad_lines=False)

In [3]:
data

,duration,mmr,server,team_1,team_2,timestamp
0,42分31秒,Challenger,cn,"賽特,葛雷夫,星朵拉,伊澤瑞爾,亞歷斯塔","鄂爾,赫克林,勒布朗,好運姐,雷歐娜",2020/12/26 19:10
1,40分0秒,Challenger,cn,"賽特,塔莉雅,星朵拉,燼,巴德","凱能,歐拉夫,奧莉安娜,凱莎,雷歐娜",2020/12/26 20:10
2,35分0秒,Challenger,cn,"卡蜜兒,史瓦妮,奧莉安娜,好運姐,亞歷斯塔","鄂爾,葛雷夫,柔伊,燼,雷歐娜",2020/12/25 20:10

In [4]:
secondDuration = []

In [5]:
#transfer chinese time to seconds
for time in data['duration']:
    timeList = time.replace('分',' ').replace('秒',' ').split()
    secondsTime = int(timeList[0]) * 60 + int(timeList[1])
    secondDuration.append(secondsTime)

In [6]:
data['duration'] = secondDuration
data

,duration,mmr,server,team_1,team_2,timestamp
0,2551,Challenger,cn,"賽特,葛雷夫,星朵拉,伊澤瑞爾,亞歷斯塔","鄂爾,赫克林,勒布朗,好運姐,雷歐娜",2020/12/26 19:10
1,2400,Challenger,cn,"賽特,塔莉雅,星朵拉,燼,巴德","凱能,歐拉夫,奧莉安娜,凱莎,雷歐娜",2020/12/26 20:10
2,2100,Challenger,cn,"卡蜜兒,史瓦妮,奧莉安娜,好運姐,亞歷斯塔","鄂爾,葛雷夫,柔伊,燼,雷歐娜",2020/12/25 20:10

In [7]:
top1List = []
jg1List = []
mid1List = []
ad1List = []
sup1List = []
top2List = []
jg2List = []
mid2List = []
ad2List = []
sup2List = []

In [8]:
#split team1 champions
for team1 in data['team_1']:
    team1List = team1.replace(',',' ').split()
    top1,jg1,mid1,ad1,sup1 = team1List
    top1List.append(top1)
    jg1List.append(jg1)
    mid1List.append(mid1)
    ad1List.append(ad1)
    sup1List.append(sup1)

In [9]:
data['top1'] = top1List
data['jg1'] = jg1List
data['mid1'] = mid1List
data['ad1'] = ad1List
data['sup1'] = sup1List
del data['team_1']
data

,duration,mmr,server,team_2,timestamp,top1,jg1,mid1,ad1,sup1
0,2551,Challenger,cn,"鄂爾,赫克林,勒布朗,好運姐,雷歐娜",2020/12/26 19:10,賽特,葛雷夫,星朵拉,伊澤瑞爾,亞歷斯塔
1,2400,Challenger,cn,"凱能,歐拉夫,奧莉安娜,凱莎,雷歐娜",2020/12/26 20:10,賽特,塔莉雅,星朵拉,燼,巴德
2,2100,Challenger,cn,"鄂爾,葛雷夫,柔伊,燼,雷歐娜",2020/12/25 20:10,卡蜜兒,史瓦妮,奧莉安娜,好運姐,亞歷斯塔

In [10]:
#split team2 champions
for team2 in data['team_2']:
    team2List = team2.replace(',',' ').split()
    top2,jg2,mid2,ad2,sup2 = team2List
    top2List.append(top2)
    jg2List.append(jg2)
    mid2List.append(mid2)
    ad2List.append(ad2)
    sup2List.append(sup2)

In [11]:
data['top2'] = top2List
data['jg2'] = jg2List
data['mid2'] = mid2List
data['ad2'] = ad2List
data['sup2'] = sup2List
del data['team_2']
data

,duration,mmr,server,timestamp,top1,jg1,mid1,ad1,sup1,top2,jg2,mid2,ad2,sup2
0,2551,Challenger,cn,2020/12/26 19:10,賽特,葛雷夫,星朵拉,伊澤瑞爾,亞歷斯塔,鄂爾,赫克林,勒布朗,好運姐,雷歐娜
1,2400,Challenger,cn,2020/12/26 20:10,賽特,塔莉雅,星朵拉,燼,巴德,凱能,歐拉夫,奧莉安娜,凱莎,雷歐娜
2,2100,Challenger,cn,2020/12/25 20:10,卡蜜兒,史瓦妮,奧莉安娜,好運姐,亞歷斯塔,鄂爾,葛雷夫,柔伊,燼,雷歐娜

In [12]:
#角色分類

#坦克: 開戰型
tankInitiate = ['阿姆姆','墨菲特','賽恩','古拉格斯','茂凱','鄂爾','賽特','札克','吶兒',
                '努努和威朗普','拉姆斯','史加納','史瓦妮','嘉文四世']
#坦克: 阻擋型
tankDefense = ['科加斯','慎','波比','蒙多醫生']

#鬥士: 續戰型
fighterContinue = ['特朗德','烏迪爾','達瑞斯','弗力貝爾','蓋倫','歐拉夫','納瑟斯','伊羅旖',
                  '沃維克','約瑞科','剛普朗克','烏爾加特','赫克林','雷珂煞','菲艾','趙信']
#鬥士: 爆發型
fighterBurst = ['雷玟','雷尼克頓','潘森','厄薩斯','克雷德','杰西','悟空','李星']

#鬥士: 全能型
fighterAlmighty = ['菲歐拉','賈克斯','伊瑞莉雅','卡蜜兒','犽宿','泰達米爾','犽凝','易大師']

#刺客
assassin = ['阿璃','塔隆','飛斯','雷葛爾','阿卡莉','葵恩','卡力斯','艾克','伊芙琳','慨影',
            '薩科','夜曲','劫','卡特蓮娜','勒布朗','卡薩丁','黛安娜','派克','姬亞娜']

#法師: 站樁型
mageStand = ['維克特','漢默丁格','卡爾瑟斯','齊勒斯','艾妮維亞','希格斯']

#法師: 控制型
mageControl = ['麗珊卓','馬爾札哈','塔莉雅','逆命','費德提克','莉莉亞','妮可','奧莉安娜']

#法師: 拉打型
magePullhit = ['凱爾','阿祈爾','翱銳龍獸','卡莎碧雅']

#法師: 坦克型
mageTank = ['斯溫','藍寶','魔鬥凱薩','弗拉迪米爾','凱能','賽勒斯','辛吉德','加里歐']

#法師: 爆發型
mageBurst = ['拉克絲','威寇茲','布蘭德','安妮','伊莉絲','雷茲','奈德麗','希瓦娜','柔依','星朵拉','維迦','瑟菈紛','枷蘿','柔伊']

#射手: 技能型
adSkill = ['路西恩','伊澤瑞爾','庫奇','葛雷夫','燼','凱莎','好運姐','煞蜜拉','亞菲利歐','姍娜','剎雅']

#射手: 強化型
adStrengthen = ['寇格魔','圖奇','達瑞文','汎','崔絲塔娜','凱特琳','吉茵珂絲']

#射手: 增益型
adBenefit = ['希維爾','克黎思妲','鏡爪','艾希','提摩','法洛士']

#輔助: 開戰型
supportInitiate = ['布里茨','雷歐娜','納帝魯斯','瑟雷西','亞歷斯塔','銳兒','銳空']

#輔助: 保牌型
supportProtect = ['娜米','貪啃奇','塔里克','露璐','魔甘娜','卡瑪','埃爾文','珍娜','悠咪','極靈','巴德','布郎姆','索娜','索拉卡']

charactersDict = {'坦克開戰型':tankInitiate,'坦克阻擋型':tankDefense,'鬥士續戰型':fighterContinue,'鬥士爆發型':fighterBurst,
             '鬥士全能型':fighterAlmighty,'刺客':assassin,'法師站樁型':mageStand,'法師控制型':mageControl,
              '法師拉打型':magePullhit,'法師坦克型':mageTank,'法師爆發型':mageBurst,'射手技能型':adSkill,
             '射手強化型':adStrengthen,'射手增益型':adBenefit,'輔助開戰型':supportInitiate,'輔助保牌型':supportProtect}

In [13]:
#Classify
top1type = []
jg1type = []
mid1type = []
ad1type = []
sup1type = []
top2type = []
jg2type = []
mid2type = []
ad2type = []
sup2type = []
for i in range(len(data)):
    for j in charactersDict:
        types = charactersDict[j]
        if data.loc[i]['top1'] in types:
            top1type.append(j)
        if data.loc[i]['jg1'] in types:
            jg1type.append(j)
        if data.loc[i]['mid1'] in types:
            mid1type.append(j)
        if data.loc[i]['ad1'] in types:
            ad1type.append(j)
        if data.loc[i]['sup1'] in types:
            sup1type.append(j)
        if data.loc[i]['top2'] in types:
            top2type.append(j)
        if data.loc[i]['jg2'] in types:
            jg2type.append(j)
        if data.loc[i]['mid2'] in types:
            mid2type.append(j)
        if data.loc[i]['ad2'] in types:
            ad2type.append(j)
        if data.loc[i]['sup2'] in types:
            sup2type.append(j)

In [14]:
mid2type

['刺客', '法師控制型', '法師爆發型']

In [15]:
data['top1type'] = top1type
data['jg1type'] = jg1type
data['mid1type'] = mid1type
data['ad1type'] = ad1type
data['sup1type'] = sup1type
data['top2type'] = top2type
data['jg2type'] = jg2type
data['mid2type'] = mid2type
data['ad2type'] = ad2type
data['sup2type'] = sup2type
data

,duration,mmr,server,timestamp,top1,jg1,mid1,ad1,sup1,top2,...,top1type,jg1type,mid1type,ad1type,sup1type,top2type,jg2type,mid2type,ad2type,sup2type
0,2551,Challenger,cn,2020/12/26 19:10,賽特,葛雷夫,星朵拉,伊澤瑞爾,亞歷斯塔,鄂爾,...,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型,坦克開戰型,鬥士續戰型,刺客,射手技能型,輔助開戰型
1,2400,Challenger,cn,2020/12/26 20:10,賽特,塔莉雅,星朵拉,燼,巴德,凱能,...,坦克開戰型,法師控制型,法師爆發型,射手技能型,輔助保牌型,法師坦克型,鬥士續戰型,法師控制型,射手技能型,輔助開戰型
2,2100,Challenger,cn,2020/12/25 20:10,卡蜜兒,史瓦妮,奧莉安娜,好運姐,亞歷斯塔,鄂爾,...,鬥士全能型,坦克開戰型,法師控制型,射手技能型,輔助開戰型,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型

In [16]:
typeData = data
del typeData['top1']
del typeData['jg1']
del typeData['mid1']
del typeData['ad1']
del typeData['sup1']
del typeData['top2']
del typeData['jg2']
del typeData['mid2']
del typeData['ad2']
del typeData['sup2']
typeData

,duration,mmr,server,timestamp,top1type,jg1type,mid1type,ad1type,sup1type,top2type,jg2type,mid2type,ad2type,sup2type
0,2551,Challenger,cn,2020/12/26 19:10,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型,坦克開戰型,鬥士續戰型,刺客,射手技能型,輔助開戰型
1,2400,Challenger,cn,2020/12/26 20:10,坦克開戰型,法師控制型,法師爆發型,射手技能型,輔助保牌型,法師坦克型,鬥士續戰型,法師控制型,射手技能型,輔助開戰型
2,2100,Challenger,cn,2020/12/25 20:10,鬥士全能型,坦克開戰型,法師控制型,射手技能型,輔助開戰型,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型

In [17]:
character = typeData.copy()
character

,duration,mmr,server,timestamp,top1type,jg1type,mid1type,ad1type,sup1type,top2type,jg2type,mid2type,ad2type,sup2type
0,2551,Challenger,cn,2020/12/26 19:10,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型,坦克開戰型,鬥士續戰型,刺客,射手技能型,輔助開戰型
1,2400,Challenger,cn,2020/12/26 20:10,坦克開戰型,法師控制型,法師爆發型,射手技能型,輔助保牌型,法師坦克型,鬥士續戰型,法師控制型,射手技能型,輔助開戰型
2,2100,Challenger,cn,2020/12/25 20:10,鬥士全能型,坦克開戰型,法師控制型,射手技能型,輔助開戰型,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型

In [18]:
del character['duration']
del character['mmr']
del character['server']
del character['timestamp']
character

,top1type,jg1type,mid1type,ad1type,sup1type,top2type,jg2type,mid2type,ad2type,sup2type
0,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型,坦克開戰型,鬥士續戰型,刺客,射手技能型,輔助開戰型
1,坦克開戰型,法師控制型,法師爆發型,射手技能型,輔助保牌型,法師坦克型,鬥士續戰型,法師控制型,射手技能型,輔助開戰型
2,鬥士全能型,坦克開戰型,法師控制型,射手技能型,輔助開戰型,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型

In [19]:
test = character.copy()
test

,top1type,jg1type,mid1type,ad1type,sup1type,top2type,jg2type,mid2type,ad2type,sup2type
0,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型,坦克開戰型,鬥士續戰型,刺客,射手技能型,輔助開戰型
1,坦克開戰型,法師控制型,法師爆發型,射手技能型,輔助保牌型,法師坦克型,鬥士續戰型,法師控制型,射手技能型,輔助開戰型
2,鬥士全能型,坦克開戰型,法師控制型,射手技能型,輔助開戰型,坦克開戰型,射手技能型,法師爆發型,射手技能型,輔助開戰型

In [20]:
team1 = ['top1type','jg1type','mid1type','ad1type','sup1type']
team2 = ['top2type','jg2type','mid2type','ad2type','sup2type']

In [21]:
#Record types of each team composition
for i in range(len(test)):
    tankInitiate,tankDefense,fighterContinue,fighterBurst,fighterAlmighty,assassin,mageStand,mageControl,magePullhit,mageTank,mageBurst,adSkill,adStrengthen,adBenefit,supportInitiate,supportProtect = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    for j in range(len(team1)):
        if test.loc[i][team1[j]] == '坦克開戰型':
            tankInitiate += 1
        if test.loc[i][team1[j]] == '坦克阻擋型':
            tankDefense += 1
        if test.loc[i][team1[j]] == '鬥士續戰型':
            fighterContinue += 1
        if test.loc[i][team1[j]] == '鬥士爆發型':
            fighterBurst += 1
        if test.loc[i][team1[j]] == '鬥士全能型':
            fighterAlmighty += 1
        if test.loc[i][team1[j]] == '刺客':
            assassin += 1
        if test.loc[i][team1[j]] == '法師站樁型':
            mageStand += 1
        if test.loc[i][team1[j]] == '法師控制型':
            mageControl += 1
        if test.loc[i][team1[j]] == '法師拉打型':
            magePullhit += 1
        if test.loc[i][team1[j]] == '法師坦克型':
            mageTank += 1
        if test.loc[i][team1[j]] == '法師爆發型':
            mageBurst += 1
        if test.loc[i][team1[j]] == '射手技能型':
            adSkill += 1
        if test.loc[i][team1[j]] == '射手強化型':
            adStrengthen += 1
        if test.loc[i][team1[j]] == '射手增益型':
            adBenefit += 1
        if test.loc[i][team1[j]] == '輔助開戰型':
            supportInitiate += 1
        if test.loc[i][team1[j]] == '輔助保牌型':
            supportProtect += 1
    test.loc[i, '坦克開戰型1'] = tankInitiate      
    test.loc[i, '坦克阻擋型1'] = tankDefense
    test.loc[i, '鬥士續戰型1'] = fighterContinue
    test.loc[i, '鬥士爆發型1'] = fighterBurst
    test.loc[i, '鬥士全能型1'] = fighterAlmighty
    test.loc[i, '刺客1'] = assassin
    test.loc[i, '法師站樁型1'] = mageStand
    test.loc[i, '法師控制型1'] = mageControl
    test.loc[i, '法師拉打型1'] = magePullhit
    test.loc[i, '法師坦克型1'] = mageTank
    test.loc[i, '法師爆發型1'] = mageBurst
    test.loc[i, '射手技能型1'] = adSkill
    test.loc[i, '射手強化型1'] = adStrengthen
    test.loc[i, '射手增益型1'] = adBenefit
    test.loc[i, '輔助開戰型1'] = supportInitiate
    test.loc[i, '輔助保牌型1'] = supportProtect
    
    tankInitiate,tankDefense,fighterContinue,fighterBurst,fighterAlmighty,assassin,mageStand,mageControl,magePullhit,mageTank,mageBurst,adSkill,adStrengthen,adBenefit,supportInitiate,supportProtect = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    
    for j in range(len(team2)):
        if test.loc[i][team2[j]] == '坦克開戰型':
            tankInitiate += 1
        if test.loc[i][team2[j]] == '坦克阻擋型':
            tankDefense += 1
        if test.loc[i][team2[j]] == '鬥士續戰型':
            fighterContinue += 1
        if test.loc[i][team2[j]] == '鬥士爆發型':
            fighterBurst += 1
        if test.loc[i][team2[j]] == '鬥士全能型':
            fighterAlmighty += 1
        if test.loc[i][team2[j]] == '刺客':
            assassin += 1
        if test.loc[i][team2[j]] == '法師站樁型':
            mageStand += 1
        if test.loc[i][team2[j]] == '法師控制型':
            mageControl += 1
        if test.loc[i][team2[j]] == '法師拉打型':
            magePullhit += 1
        if test.loc[i][team2[j]] == '法師坦克型':
            mageTank += 1
        if test.loc[i][team2[j]] == '法師爆發型':
            mageBurst += 1
        if test.loc[i][team2[j]] == '射手技能型':
            adSkill += 1
        if test.loc[i][team2[j]] == '射手強化型':
            adStrengthen += 1
        if test.loc[i][team2[j]] == '射手增益型':
            adBenefit += 1
        if test.loc[i][team2[j]] == '輔助開戰型':
            supportInitiate += 1
        if test.loc[i][team2[j]] == '輔助保牌型':
            supportProtect += 1
    test.loc[i, '坦克開戰型2'] = tankInitiate
    test.loc[i, '坦克阻擋型2'] = tankDefense
    test.loc[i, '鬥士續戰型2'] = fighterContinue
    test.loc[i, '鬥士爆發型2'] = fighterBurst
    test.loc[i, '鬥士全能型2'] = fighterAlmighty
    test.loc[i, '刺客2'] = assassin
    test.loc[i, '法師站樁型2'] = mageStand
    test.loc[i, '法師控制型2'] = mageControl
    test.loc[i, '法師拉打型2'] = magePullhit
    test.loc[i, '法師坦克型2'] = mageTank
    test.loc[i, '法師爆發型2'] = mageBurst
    test.loc[i, '射手技能型2'] = adSkill
    test.loc[i, '射手強化型2'] = adStrengthen
    test.loc[i, '射手增益型2'] = adBenefit
    test.loc[i, '輔助開戰型2'] = supportInitiate
    test.loc[i, '輔助保牌型2'] = supportProtect

In [22]:
del test['top1type']
del test['jg1type']
del test['mid1type']
del test['ad1type']
del test['sup1type']
del test['top2type']
del test['jg2type']
del test['mid2type']
del test['ad2type']
del test['sup2type']
test

,坦克開戰型1,坦克阻擋型1,鬥士續戰型1,鬥士爆發型1,鬥士全能型1,刺客1,法師站樁型1,法師控制型1,法師拉打型1,法師坦克型1,...,法師站樁型2,法師控制型2,法師拉打型2,法師坦克型2,法師爆發型2,射手技能型2,射手強化型2,射手增益型2,輔助開戰型2,輔助保牌型2
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0

In [23]:
#Add dutation in dataframe
test['duration'] = data['duration']
test

,坦克開戰型1,坦克阻擋型1,鬥士續戰型1,鬥士爆發型1,鬥士全能型1,刺客1,法師站樁型1,法師控制型1,法師拉打型1,法師坦克型1,...,法師控制型2,法師拉打型2,法師坦克型2,法師爆發型2,射手技能型2,射手強化型2,射手增益型2,輔助開戰型2,輔助保牌型2,duration
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2551
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,2400
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,2100

In [24]:
import pandas as pd
data = pd.read_csv('characters.csv')
data

,坦克開戰型1,坦克阻擋型1,鬥士續戰型1,鬥士爆發型1,鬥士全能型1,刺客1,法師站樁型1,法師控制型1,法師拉打型1,法師坦克型1,...,法師拉打型2,法師坦克型2,法師爆發型2,射手技能型2,射手強化型2,射手增益型2,輔助開戰型2,輔助保牌型2,duration,result
0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,662,1
1,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,662,1
2,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,662,1
3,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,662,1
4,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,694,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5003,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,2685,0
5004,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2685,0
5005,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,2685,1
5006,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,2729,0
5007,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2729,1

In [25]:
#Split into features and target
from sklearn.model_selection import train_test_split
features = data.columns
features = features.drop('result')
target = data['result']

# Split data into test and train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data[features], target, test_size=0.3, random_state=12345)

# Normalize Features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_nor = scaler.fit_transform(X_train)
X_test_nor = scaler.fit_transform(X_test)

In [26]:
#Use LogisticRegression to classify predict
from sklearn.linear_model  import LogisticRegression
from sklearn.metrics import accuracy_score
lr=LogisticRegression()
lr.fit(X_train_nor,y_train)

y_pred = lr.predict(X_test_nor)
print ("So, Our accuracy Score is: {}".format(round(accuracy_score(y_pred, y_test),4)))

So, Our accuracy Score is: 0.8004

In [27]:
test

,坦克開戰型1,坦克阻擋型1,鬥士續戰型1,鬥士爆發型1,鬥士全能型1,刺客1,法師站樁型1,法師控制型1,法師拉打型1,法師坦克型1,...,法師控制型2,法師拉打型2,法師坦克型2,法師爆發型2,射手技能型2,射手強化型2,射手增益型2,輔助開戰型2,輔助保牌型2,duration
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2551
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,2400
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,2100

In [28]:
# Normalize test Features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
test_nor = scaler.fit_transform(test)

In [29]:
#Show the predict result
lr.predict(test_nor)

array([0, 0, 1], dtype=int64)

In [30]:
#Show the predict result probability
lr.predict_proba(test_nor)

array([[0.87910616, 0.12089384],
       [0.62449123, 0.37550877],
       [0.08962951, 0.91037049]])